### ISSUE TITLE
[두번째 페이지 - 레이아웃] Todo 페이지 레이아웃 작성

### ISSUE THREAD

**Issue by imhjnoh** [extreme-todo/frontend#35]
<img width="1445" alt="Screenshot 2023-08-01 at 21 07 09" src="https://github.com/extreme-todo/frontend/assets/56210700/98a7a428-3821-4499-bef1-7f28e91d5ef8">

### 위 페이지의 레이아웃 작성 (위치만 잡는 작업이라 테스트 코드 생략)
- [x] 시계 영역
- [x] 왼쪽 버튼 영역
- [x] 오른쪽 버튼 영역
- [x] 중앙 "지금 할 일" 영역
