### ISSUE TITLE
todo module 만들기

### ISSUE THREAD

**Issue by ferrariRoma** [extreme-todo/frontend#89]
- [x] 일단 고민을 해보기
- [x] 구현 가능성을 따지고 최소 단위로 구현해보기
  - [x] indexedDB와 todosApi를 class parameter로 받는 module class 만들기
  - [x] interface 만들기
- [ ] todo의 id를 바꾸기
  - [ ] nest에 반영하기
  - [ ] indexedDB에 반영하기
- [ ] on/off 훅 만들기
- 이까지만 해두고 todosApi를 일단 사용하는 것으로 만들기
  - 이유는 on/off 모두 되는 class를 적용해버리기에는 아직 준비가 안 된 부분도 있다고 판단해서 현재 잘 작동하고 있는 todosApi를 적용한 버전으로 출시를 하고 PWA를 적용할 때 이 버전을 적용하는 것으로 함
